#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright 2026 occamsshavingkit/sw-dev-team-template contributors
#
# tests/upgrade/test-manifest-handoff-activity-issue-276.sh
#
# fw-adr-0023 D2 Option S (v1.2.0): handoff JSON files are now fully static
# after creation. The handoff-record-activity.py hook writes runtime telemetry
# to docs/handoffs/<task_id>.activity.jsonl (gitignored) instead of mutating
# the handoff JSON. manifest_file_sha_normalized is removed; all files are
# hashed raw via manifest_file_sha.
#
# This test file is updated from its issue-#276 origin to reflect the new
# sidecar model. The normalizer tests (F1/F2/F5 from the original) are
# replaced with verification that:
#
#   NEW-F1. manifest_file_sha agrees with sha256sum raw (no normalizer path).
#   NEW-F2. A handoff JSON file that does NOT change between write and verify
#           produces no drift (manifest_verify rc=0).
#   NEW-F3. A change to a durable field (status) IS detected (rc=1, drift).
#   NEW-F4. A non-handoff file is hashed raw: two different files differ.
#   NEW-F5. The v1.2.0 migration strips "activity" from handoff JSON files
#           and exports entries to the sidecar JSONL.
#
# IEEE 1008-1987 §3.2 — features under test.

set -u

repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
manifest_lib="$repo_root/scripts/lib/manifest.sh"
migration="$repo_root/migrations/v1.2.0.sh"
# shellcheck source=scripts/lib/manifest.sh
source "$manifest_lib"

tmp="$(mktemp -d -t manifest-276-XXXXXX)"
keep=0
[[ "${1:-}" == "--keep" ]] && keep=1
trap 'if [[ $keep -eq 0 ]]; then rm -rf "$tmp"; else echo "(kept $tmp for inspection)" >&2; fi' EXIT

fail=0
pass=0

check() {
  local label="$1"; shift
  if "$@" >/dev/null 2>&1; then
    echo "  PASS: $label"
    pass=$((pass + 1))
  else
    echo "  FAIL: $label" >&2
    fail=$((fail + 1))
  fi
}

check_output() {
  local label="$1"; shift
  local pattern="$1"; shift
  local out
  out=$("$@" 2>&1) || true
  if echo "$out" | grep -qF "$pattern"; then
    echo "  PASS: $label"
    pass=$((pass + 1))
  else
    echo "  FAIL: $label (pattern='$pattern' not found in output)" >&2
    echo "        output was: $out" >&2
    fail=$((fail + 1))
  fi
}

# ---------------------------------------------------------------------------
# Fixture: a minimal handoff JSON WITHOUT an activity key (post-migration).
# ---------------------------------------------------------------------------
HANDOFF_RELPATH="docs/handoffs/test-276-handoff.json"
mkdir -p "$tmp/docs/handoffs"

cat > "$tmp/$HANDOFF_RELPATH" << 'EOF'
{
  "schema": "https://example.invalid/sw-dev-team-template/handoff.schema.json",
  "task_id": "test-276",
  "status": "active",
  "verification": {
    "tests": []
  }
}
EOF

# ---------------------------------------------------------------------------
# NEW-F1. manifest_file_sha produces the same result as sha256sum raw.
# ---------------------------------------------------------------------------
echo "-- NEW-F1: manifest_file_sha matches raw sha256sum --"

sha_lib=$(manifest_file_sha "$tmp/$HANDOFF_RELPATH")
sha_raw=$(sha256sum "$tmp/$HANDOFF_RELPATH" | awk '{print $1}')

if [[ "$sha_lib" == "$sha_raw" && -n "$sha_lib" ]]; then
  echo "  PASS: NEW-F1 — manifest_file_sha matches sha256sum raw"
  pass=$((pass + 1))
else
  echo "  FAIL: NEW-F1 — lib='$sha_lib' raw='$sha_raw'" >&2
  fail=$((fail + 1))
fi

# ---------------------------------------------------------------------------
# NEW-F2. A handoff JSON file that does NOT change produces no drift.
# Write manifest from baseline; verify — must be clean.
# ---------------------------------------------------------------------------
echo ""
echo "-- NEW-F2: static handoff file produces no drift --"

manifest_path="$tmp/TEMPLATE_MANIFEST.lock"
{
  echo "# TEMPLATE_MANIFEST.lock — per FW-ADR-0002"
  echo "# Generated by test-manifest-handoff-activity-issue-276.sh"
  echo "# Format: <sha256>  <project-relative path>"
  echo "#"
  printf '%s  %s\n' "$(manifest_file_sha "$tmp/$HANDOFF_RELPATH")" "$HANDOFF_RELPATH"
} > "$manifest_path"

verify_output=$(manifest_verify "$tmp" "$manifest_path" 2>&1)
verify_rc=$?

if [[ $verify_rc -eq 0 ]]; then
  echo "  PASS: NEW-F2 — manifest_verify rc=0 (no drift on static file)"
  pass=$((pass + 1))
else
  echo "  FAIL: NEW-F2 — manifest_verify rc=$verify_rc" >&2
  echo "        output: $verify_output" >&2
  fail=$((fail + 1))
fi

if echo "$verify_output" | grep -qiF "drift"; then
  echo "  FAIL: NEW-F2 — 'drift' appeared in verify output unexpectedly" >&2
  fail=$((fail + 1))
else
  echo "  PASS: NEW-F2 — 'drift' absent from verify output"
  pass=$((pass + 1))
fi

# ---------------------------------------------------------------------------
# NEW-F3. A change to the durable "status" field IS detected.
# ---------------------------------------------------------------------------
echo ""
echo "-- NEW-F3: durable contract change (status field) detected --"

# Write manifest from current state.
{
  echo "# TEMPLATE_MANIFEST.lock — per FW-ADR-0002"
  echo "# Format: <sha256>  <project-relative path>"
  printf '%s  %s\n' "$(manifest_file_sha "$tmp/$HANDOFF_RELPATH")" "$HANDOFF_RELPATH"
} > "$manifest_path"

# Mutate the durable "status" field.
python3 - "$tmp/$HANDOFF_RELPATH" << 'PYEOF'
import json, sys
from pathlib import Path
p = Path(sys.argv[1])
doc = json.loads(p.read_text(encoding="utf-8"))
doc["status"] = "completed"
p.write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8")
PYEOF

verify_output_durable=$(manifest_verify "$tmp" "$manifest_path" 2>&1)
verify_rc_durable=$?

if [[ $verify_rc_durable -ne 0 ]]; then
  echo "  PASS: NEW-F3 — manifest_verify rc=$verify_rc_durable (drift detected)"
  pass=$((pass + 1))
else
  echo "  FAIL: NEW-F3 — manifest_verify rc=0 but status was mutated" >&2
  echo "        output: $verify_output_durable" >&2
  fail=$((fail + 1))
fi

if echo "$verify_output_durable" | grep -qiF "drift"; then
  echo "  PASS: NEW-F3 — 'drift' reported for durable contract change"
  pass=$((pass + 1))
else
  echo "  FAIL: NEW-F3 — 'drift' not reported; durable change was silently missed" >&2
  fail=$((fail + 1))
fi

# ---------------------------------------------------------------------------
# NEW-F4. Two files with different content produce different raw hashes.
# ---------------------------------------------------------------------------
echo ""
echo "-- NEW-F4: different files produce different hashes --"

cat > "$tmp/file-a.md" << 'EOF'
content A
EOF
cat > "$tmp/file-b.md" << 'EOF'
content B
EOF

sha_a=$(manifest_file_sha "$tmp/file-a.md")
sha_b=$(manifest_file_sha "$tmp/file-b.md")

if [[ "$sha_a" != "$sha_b" && -n "$sha_a" && -n "$sha_b" ]]; then
  echo "  PASS: NEW-F4 — different files produce different hashes"
  pass=$((pass + 1))
else
  echo "  FAIL: NEW-F4 — expected different hashes, got same: '$sha_a'" >&2
  fail=$((fail + 1))
fi

# ---------------------------------------------------------------------------
# NEW-F5. Migration v1.2.0 strips "activity" from handoff JSON and exports
#         non-empty entries to the sidecar JSONL.
# ---------------------------------------------------------------------------
echo ""
echo "-- NEW-F5: migration strips activity, exports to sidecar --"

MIGTEST_RELPATH="docs/handoffs/test-mig-handoff.json"
mkdir -p "$tmp/docs/handoffs"

cat > "$tmp/$MIGTEST_RELPATH" << 'EOF'
{
  "task_id": "test-mig",
  "status": "active",
  "activity": [
    {"name": "Bash: ls", "result": "passed", "actor_role": "hook", "timestamp": "2026-06-03T00:00:00Z"}
  ],
  "verification": {"tests": []}
}
EOF

PROJECT_ROOT="$tmp" bash "$migration" >/dev/null

# activity key must be gone.
has_activity=$(python3 -c "
import json, sys
doc = json.load(open(sys.argv[1]))
print('yes' if 'activity' in doc else 'no')
" "$tmp/$MIGTEST_RELPATH")

if [[ "$has_activity" == "no" ]]; then
  echo "  PASS: NEW-F5 — activity key removed from handoff JSON"
  pass=$((pass + 1))
else
  echo "  FAIL: NEW-F5 — activity key still present after migration" >&2
  fail=$((fail + 1))
fi

# Sidecar must exist with 1 JSONL line.
sidecar="$tmp/docs/handoffs/test-mig.activity.jsonl"
if [[ -f "$sidecar" ]]; then
  line_count=$(wc -l < "$sidecar")
  if [[ "$line_count" -eq 1 ]]; then
    echo "  PASS: NEW-F5 — sidecar has 1 entry"
    pass=$((pass + 1))
  else
    echo "  FAIL: NEW-F5 — sidecar has $line_count lines (expected 1)" >&2
    fail=$((fail + 1))
  fi
  # Entry must be valid JSON.
  if python3 -c "import json; json.loads(open('$sidecar').readline())" 2>/dev/null; then
    echo "  PASS: NEW-F5 — sidecar entry is valid JSON"
    pass=$((pass + 1))
  else
    echo "  FAIL: NEW-F5 — sidecar entry is not valid JSON" >&2
    fail=$((fail + 1))
  fi
else
  echo "  FAIL: NEW-F5 — sidecar file not created" >&2
  fail=$((fail + 1))
fi

# Idempotent re-run: second run should be a no-op (no sidecar duplication).
PROJECT_ROOT="$tmp" bash "$migration" >/dev/null
line_count_after=$(wc -l < "$sidecar")
if [[ "$line_count_after" -eq 1 ]]; then
  echo "  PASS: NEW-F5 — migration is idempotent (sidecar not doubled)"
  pass=$((pass + 1))
else
  echo "  FAIL: NEW-F5 — sidecar grew on second run ($line_count_after lines)" >&2
  fail=$((fail + 1))
fi

# ---------------------------------------------------------------------------
# NEW-F6. Migration v1.2.0 leaves an EMPTY "activity": [] BYTE-IDENTICAL.
#         (fix for upgrade-conflict on v1.1.0→v1.3.0 downstream paths)
# ---------------------------------------------------------------------------
echo ""
echo "-- NEW-F6: empty activity array — file left byte-identical (no SHA change) --"

MIGTEST_EMPTY_RELPATH="docs/handoffs/test-empty-activity.json"
mkdir -p "$tmp/docs/handoffs"

cat > "$tmp/$MIGTEST_EMPTY_RELPATH" << 'EOF'
{
  "task_id": "test-empty",
  "status": "active",
  "activity": [],
  "verification": {"tests": []}
}
EOF

before_sha=$(sha256sum "$tmp/$MIGTEST_EMPTY_RELPATH" | awk '{print $1}')

PROJECT_ROOT="$tmp" bash "$migration" >/dev/null

after_sha=$(sha256sum "$tmp/$MIGTEST_EMPTY_RELPATH" | awk '{print $1}')

if [[ "$before_sha" == "$after_sha" ]]; then
  echo "  PASS: NEW-F6 — empty-activity file SHA unchanged (byte-identical)"
  pass=$((pass + 1))
else
  echo "  FAIL: NEW-F6 — SHA changed! empty-activity file was rewritten" >&2
  echo "        before=$before_sha after=$after_sha" >&2
  fail=$((fail + 1))
fi

# activity key must still be present (we left it in place).
has_activity_f6=$(python3 -c "
import json, sys
doc = json.load(open(sys.argv[1]))
print('yes' if 'activity' in doc else 'no')
" "$tmp/$MIGTEST_EMPTY_RELPATH")

if [[ "$has_activity_f6" == "yes" ]]; then
  echo "  PASS: NEW-F6 — activity key still present (inert empty array left in place)"
  pass=$((pass + 1))
else
  echo "  FAIL: NEW-F6 — activity key was stripped (should have been left untouched)" >&2
  fail=$((fail + 1))
fi

# No sidecar should have been created.
empty_sidecar="$tmp/docs/handoffs/test-empty.activity.jsonl"
if [[ ! -f "$empty_sidecar" ]]; then
  echo "  PASS: NEW-F6 — no sidecar created for empty activity (correct)"
  pass=$((pass + 1))
else
  echo "  FAIL: NEW-F6 — sidecar created for empty activity (should not be)" >&2
  fail=$((fail + 1))
fi

# Idempotency: re-run is also a no-op.
PROJECT_ROOT="$tmp" bash "$migration" >/dev/null
after_sha2=$(sha256sum "$tmp/$MIGTEST_EMPTY_RELPATH" | awk '{print $1}')
if [[ "$before_sha" == "$after_sha2" ]]; then
  echo "  PASS: NEW-F6 — idempotent re-run: file still byte-identical"
  pass=$((pass + 1))
else
  echo "  FAIL: NEW-F6 — second run changed the file (not idempotent)" >&2
  fail=$((fail + 1))
fi

# ---------------------------------------------------------------------------
# NEW-F7. Migration v1.2.0 leaves an already-absent activity key untouched.
# ---------------------------------------------------------------------------
echo ""
echo "-- NEW-F7: absent activity key — file left byte-identical --"

MIGTEST_ABSENT_RELPATH="docs/handoffs/test-absent-activity.json"
cat > "$tmp/$MIGTEST_ABSENT_RELPATH" << 'EOF'
{
  "task_id": "test-absent",
  "status": "active",
  "verification": {"tests": []}
}
EOF

before_sha_f7=$(sha256sum "$tmp/$MIGTEST_ABSENT_RELPATH" | awk '{print $1}')
PROJECT_ROOT="$tmp" bash "$migration" >/dev/null
after_sha_f7=$(sha256sum "$tmp/$MIGTEST_ABSENT_RELPATH" | awk '{print $1}')

if [[ "$before_sha_f7" == "$after_sha_f7" ]]; then
  echo "  PASS: NEW-F7 — absent-activity file SHA unchanged (byte-identical)"
  pass=$((pass + 1))
else
  echo "  FAIL: NEW-F7 — SHA changed! absent-activity file was rewritten" >&2
  fail=$((fail + 1))
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo "PASS: $pass"
echo "FAIL: $fail"
if [[ $fail -gt 0 ]]; then
  exit 1
fi
exit 0
