#!/bin/sh
# SPDX-License-Identifier: MIT
# Copyright 2026 occamsshavingkit/sw-dev-team-template contributors
#
# scripts/archive-registers.sh - append live-register snapshots to archives.
#
# Usage:
#   scripts/archive-registers.sh [--dry-run|--apply] [--rewrite-tombstones]
#   scripts/archive-registers.sh --list
#
# Exit codes:
#   0 - success
#   1 - archival or file-system error
#   2 - usage error

set -eu

mode=dry-run
rewrite_tombstones=no
list_only=no

usage() {
  cat <<'EOF'
Usage:
  scripts/archive-registers.sh [OPTIONS]

Archive append-only snapshots of live registers into their paired archive files.
Default mode is --dry-run, which reports actions without writing files.

Options:
  --dry-run              Report planned archive updates without changing files.
  --apply                Create/update archive files by appending new snapshots.
  --rewrite-tombstones   With --apply only, replace live files with compact
                         tombstones pointing to their archives. This never runs
                         by default.
  --list                 Print source/archive pairs and exit.
  -h, --help             Show this help.

Source/archive pairs:
  docs/OPEN_QUESTIONS.md  -> docs/OPEN_QUESTIONS-ARCHIVE.md
  CUSTOMER_NOTES.md       -> docs/customer-notes-archive.md
  docs/intake-log.md      -> docs/intake-log-ARCHIVE.md
  docs/pm/RISKS.md        -> docs/pm/RISKS-ARCHIVE.md
  docs/pm/LESSONS.md      -> docs/pm/LESSONS-ARCHIVE.md
EOF
}

pairs() {
  cat <<'EOF'
docs/OPEN_QUESTIONS.md	docs/OPEN_QUESTIONS-ARCHIVE.md
CUSTOMER_NOTES.md	docs/customer-notes-archive.md
docs/intake-log.md	docs/intake-log-ARCHIVE.md
docs/pm/RISKS.md	docs/pm/RISKS-ARCHIVE.md
docs/pm/LESSONS.md	docs/pm/LESSONS-ARCHIVE.md
EOF
}

log() {
  printf '%s\n' "$*"
}

warn() {
  printf 'WARN: %s\n' "$*" >&2
}

die() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

usage_error() {
  printf 'ERROR: %s\n\n' "$*" >&2
  usage >&2
  exit 2
}

archive_header() {
  source_path=$1
  cat <<EOF
# Archive for \`$source_path\`

Append-only snapshots generated by \`scripts/archive-registers.sh --apply\`.
Do not remove historical entries from this file; keep live registers compact by
moving closed or historical content here and leaving archive pointers live.
EOF
}

checksum_for() {
  cksum < "$1" | awk '{ printf "%s:%s", $1, $2 }'
}

archive_contains_checksum() {
  archive_path=$1
  checksum=$2

  test -f "$archive_path" && grep -F "checksum=\"$checksum\"" "$archive_path" >/dev/null 2>&1
}

append_snapshot() {
  source_path=$1
  archive_path=$2
  checksum=$3
  archived_at=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
  archive_dir=$(dirname "$archive_path")

  if test ! -d "$archive_dir"; then
    mkdir -p "$archive_dir" || die "cannot create archive directory: $archive_dir"
  fi

  if test ! -f "$archive_path"; then
    archive_header "$source_path" > "$archive_path" || die "cannot create archive: $archive_path"
  fi

  {
    printf '\n<!-- archive-registers:begin source="%s" checksum="%s" archived-at="%s" -->\n\n' "$source_path" "$checksum" "$archived_at"
    printf '## Snapshot from `%s`\n\n' "$source_path"
    printf '%s `%s`\n' '- Archived at:' "$archived_at"
    printf '%s `%s`\n\n' '- Source checksum:' "$checksum"
    printf '```markdown\n'
    cat "$source_path"
    printf '\n```\n\n'
    printf '<!-- archive-registers:end source="%s" checksum="%s" -->\n' "$source_path" "$checksum"
  } >> "$archive_path" || die "cannot append archive snapshot: $archive_path"
}

rewrite_tombstone() {
  source_path=$1
  archive_path=$2
  checksum=$3
  tmp_path=${source_path}.archive-registers.$$

  {
    printf '# Archived Register Tombstone\n\n'
    printf 'Historical content from `%s` has been archived in `%s`.\n\n' "$source_path" "$archive_path"
    printf '%s `%s`\n' '- Last archived checksum:' "$checksum"
    printf '%s\n' '- To append current live content again, run `scripts/archive-registers.sh --apply`.'
  } > "$tmp_path" || die "cannot write tombstone temp file: $tmp_path"

  mv "$tmp_path" "$source_path" || die "cannot replace live register with tombstone: $source_path"
}

process_pair() {
  source_path=$1
  archive_path=$2

  if test ! -f "$source_path"; then
    warn "source missing, skipping: $source_path"
    return 0
  fi

  checksum=$(checksum_for "$source_path")

  if archive_contains_checksum "$archive_path" "$checksum"; then
    log "SKIP already archived: $source_path -> $archive_path ($checksum)"
  elif test "$mode" = dry-run; then
    if test -f "$archive_path"; then
      log "DRY-RUN would append: $source_path -> $archive_path ($checksum)"
    else
      log "DRY-RUN would create and append: $source_path -> $archive_path ($checksum)"
    fi
  else
    append_snapshot "$source_path" "$archive_path" "$checksum"
    log "APPENDED: $source_path -> $archive_path ($checksum)"
  fi

  if test "$rewrite_tombstones" = yes; then
    if archive_contains_checksum "$archive_path" "$checksum"; then
      rewrite_tombstone "$source_path" "$archive_path" "$checksum"
      log "REWROTE TOMBSTONE: $source_path -> $archive_path"
    else
      die "refusing to rewrite tombstone before archive contains checksum for $source_path"
    fi
  fi
}

while test $# -gt 0; do
  case $1 in
    --dry-run)
      mode=dry-run
      shift
      ;;
    --apply)
      mode=apply
      shift
      ;;
    --rewrite-tombstones)
      rewrite_tombstones=yes
      shift
      ;;
    --list)
      list_only=yes
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage_error "unknown option: $1"
      ;;
  esac
done

if test "$rewrite_tombstones" = yes && test "$mode" != apply; then
  usage_error "--rewrite-tombstones requires --apply"
fi

if test "$list_only" = yes; then
  pairs
  exit 0
fi

pairs | while IFS=' 	' read -r source_path archive_path; do
  test -n "$source_path" || continue
  process_pair "$source_path" "$archive_path"
done
